permalink: /:title

# Meta
title:                  Sarina Canelake
tagline:                Sarina Canelake's internet home
aboutme:                Software Engineering Manager
url:                    http://sarina.canelake.com
baseurl:                /
author:
  name:                 Sarina Canelake
  url:                  https://www.linkedin.com/in/sarinac/
  email:                sarina@canelake.com

# Custom vars
resume:                  resume/resume--sarina-canelake-2020.pdf
